#define EXECUTE_COMMUICATION true
#define NO_HARDWARE true
#define DEBUG_COMMUNICATION true
#define SIMULATION true
#define ANALYZE_INPUTS false
#define CALCULATE_ACCELERATION_VIA_INTERRUPT false
#define ALLOW_COMMAND_WHEN_AXIS_IS_ACTIVE true
#define GET_VALUES_ON_BOOTUP true
#define STEPS_PER_MM 40UL
#define PIN_ENABLE 51
#define PIN_BEEPER 53

//Default Values
#define X_AXIS_HOMING_OFFSET 20
#define Y_AXIS_HOMING_OFFSET 20
#define Z_AXIS_HOMING_OFFSET 20

#define X_AXIS_MAX_POSITION 210 - X_AXIS_HOMING_OFFSET
#define Y_AXIS_MAX_POSITION 210 - Y_AXIS_HOMING_OFFSET
#define Z_AXIS_MAX_POSITION 200 - Z_AXIS_HOMING_OFFSET

#define X_AXIS_ACCELLERATION 600
#define Y_AXIS_ACCELLERATION 600
#define Z_AXIS_ACCELLERATION 600

#define X_AXIS_MAX_SPEED 400
#define Y_AXIS_MAX_SPEED 400
#define Z_AXIS_MAX_SPEED 400




#define PROCESSOR ARDUINO_AVR_MEGA2560
#if PROCESSOR == ARDUINO_AVR_MEGA2560
    #define PROCESSOR_CYCLES_PER_MICROSECOND 16UL
#else
    #error "Unbekannter Prozessor"
#endif
#define ACCELERATION_RECALCULATION_PERIOD_IN_MILLISECONDS 4UL
#define ACCEL_RECALC_PERIOD_IN_PROCESSOR_CYLCES (ACCELERATION_RECALCULATION_PERIOD_IN_MILLISECONDS * 1000UL * PROCESSOR_CYCLES_PER_MICROSECOND)

#include "pins.h"










